input wire A, INV_OUT, INTERMEDIATE1, FINAL_OUT;
output wire MODIFIED_OUT;
and t1 (TRIGGER, A, INV_OUT);
not t2 (PAYLOAD, INTERMEDIATE1);
or t3 (MODIFIED_OUT, FINAL_OUT, PAYLOAD);
wire TRIGGER (t1);
wire PAYLOAD (t2, t3);
